# Generated by Django 5.2.5 on 2025-08-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
