# Generated by Django 5.2.5 on 2025-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_app', '0002_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary')], max_length=100)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
