# Generated by Django 5.2.5 on 2025-08-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary'), ('romance', 'Romance'), ('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy')], max_length=100),
        ),
    ]
