# Generated by Django 5.2.5 on 2025-08-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
